### ISSUE TITLE
limesdr - stream stop and recover issue when setting filter BW

### ISSUE THREAD

**Issue by guruofquality** [myriadrf/LimeSuite#100]
There is an issue with ILimeSDRStreaming::EnterSelfCalibration/ILimeSDRStreaming::ExitSelfCalibration when used while streaming. One way to cause this is to tune the filter BW while streaming from the SoapyLMS7 wrapper: https://discourse.myriadrf.org/t/example-of-configuration-for-sdr-source-block-in-pothossdr/806/5

* [ ] One issue is that the [EnterSelfCalibration and ExitSelfCalibration](https://github.com/myriadrf/LimeSuite/blob/master/src/protocols/ILimeSDRStreaming.cpp#L143) hooks dont correctly recover streaming, or at least not consistently.
* [ ] A secondary issue is that the calibration locking needs to be within the [filter cal functions](https://github.com/myriadrf/LimeSuite/blob/master/src/lms7002m/LMS7002M_filtersCalibration.cpp) so they are only used when calibrating and not when reading from the cache.

**Comment by IgnasJarusevicius** [comment]
Closing old issue.
