### ISSUE TITLE
Don't log to stdout

### ISSUE THREAD

**Issue by xmikos** [myriadrf/LimeSuite#108]
LimeSDR driver is currently not usable with my new [soapy_power](https://github.com/xmikos/soapy_power) backend in [QSpectrumAnalyzer](https://github.com/xmikos/qspectrumanalyzer), because it outputs some info to stdout. It should only write to stderr, like SoapySDR itself. Example of info logged to stdout by LimeSDR driver:

    Estimated reference clock 30.7198 MHz
    Selected reference clock 30.720 MHz
    LMS7002M values cache at /home/mikos/.limesuite/LMS7002M_cache_values.db
    ConnectionSTREAM::ConfigureFPGA_PLL(tx=20MHz, rx=10MHz)
    ConnectionSTREAM::ConfigureFPGA_PLL(tx=10MHz, rx=10MHz)
    ConnectionSTREAM::ConfigureFPGA_PLL(tx=20MHz, rx=10MHz)
    ConnectionSTREAM::ConfigureFPGA_PLL(tx=10MHz, rx=10MHz)
    ConnectionSTREAM::ConfigureFPGA_PLL(tx=40MHz, rx=40MHz)
    SetFrequency using cache values vco:1, csw:211
    L 1396720

I can temporarily fix it by ugly hacks with `os.dup2`, but this should be IMHO fixed in LimeSuite itself.

**Comment by guruofquality** [comment]
Related issue: https://github.com/myriadrf/LimeSuite/issues/58 If we get all of the prints into the logger, it will be easy to pass into SoapySDR logger, which is already taken care of.
