### ISSUE TITLE
lime-suite integration of the C LMS7002M-driver

### ISSUE THREAD

**Issue by guruofquality** [myriadrf/LimeSuite#11]
# LMS7002M-driver

LMS7002M-driver is its own stand-alone C driver project for the LMS7
- Reference here: https://github.com/myriadrf/LMS7002M-driver
- We will move the LMS7002M-driver entirely into the lime-suite tree to be built and packaged as one of the components.
# Common calibration utilities

This may become a separate issue on the tracker, but a major benefit of this work should be creating a common calibration algorithm set for both drivers.  This implies re-writing some of the calibration algorithms in C and generalizing it around the spi interface. Its definitely possible since this was actually done for the LMS7002M-driver. Hopefully we end up with a stronger and better tested calibration algorithm overall.

**Comment by IgnasJarusevicius** [comment]
Closing old issue. Re-open if still relevant
