### ISSUE TITLE
Window size control

### ISSUE THREAD

**Issue by n3qq** [myriadrf/LimeSuite#110]
Need to add window size control, I'm unable to see
communications window at the bottom (glance of top line only), tried to
move lower taskbar, no help. W10/64bit

**Comment by romeojulietthotel** [comment]
As in #90 window size control would relieve lots of problems.

**Comment by rjonaitis** [comment]
Added scrollbars and enabled resize of main window, should be good enough for now.

**Comment by romeojulietthotel** [comment]
Tested and works fine.
