### ISSUE TITLE
Can't set antenna in SoapySDR?

### ISSUE THREAD

**Issue by darkstar007** [myriadrf/LimeSuite#113]
If I do something along the lines of:

```
  antval = SoapySDRDevice_getAntenna(dev, SOAPY_SDR_RX, 0);
  fprintf(stderr, "****Antenna set to %s\n", antval);
  
  fprintf(stderr, "Setting antenna to \"LNAL\"\n");
  r = (int)SoapySDRDevice_setAntenna(dev, SOAPY_SDR_RX, 0, "LNAL");
  if (r != 0) {
    fprintf(stderr, "WARNING: Failed to set antenna!!!.\n");
  }
  
  antval = SoapySDRDevice_getAntenna(dev, SOAPY_SDR_RX, 0);
  fprintf(stderr, "****Antenna set to %s\n", antval);
  ```

It prints out:
```
Found 6 antenna(s): NONE LNAH LNAL LNAW LB1 LB2 
****Antenna set to LB1
Setting antenna to "LNAL"
[INFO] SoapyLMS7::setAntenna(Rx, 0, LNAL)
****Antenna set to LB1
```

Which seems to show that it hasn't changed the antenna setting?

I'll attach my simple test code (renamed as github obviously doesn't think anyone would want to upload a C source file in a bug report....)

Thanks,

Matt
[test_ant.txt](https://github.com/myriadrf/LimeSuite/files/848959/test_ant.txt)

**Comment by guruofquality** [comment]
Thanks for the report. It was a logic bug reading back the selected path. The antenna setting was correct, just not the logic to report the correct antenna. Its fixed now: https://github.com/myriadrf/LimeSuite/commit/43c2af4d010348d231b740299b3af6f06bc10b52
