### ISSUE TITLE
No API in LimeSuite to disable NCO

### ISSUE THREAD

**Issue by f4exb** [myriadrf/LimeSuite#121]
Hello,

I haven't seen anywhere in the API (lime/LimeSuite.h) a way to disable the NCO once it is enabled with LMS_SetNCOFrequency. There is no explicit enable boolean variable (unlike LMS_SetGFIRLPF for example) nor setting the NCO frequency to zero does that apparently.

If I got it right this is done in LMS7_Device class simply with this instruction: Modify_SPI_Reg_bits(LMS7param(CMIX_BYP_RXTSP), 1);

Alas there is no way to activate it unless you init the device.

It would be nice to have a way to just disable or re-enable the NCO via an API call.

Best regards.

**Comment by f4exb** [comment]
My bad... LMS_SetNCOIndex just does that

**Comment by IgnasJarusevicius** [comment]
Hi,
thanks for observation, I will update LMS_SetNCOIndex() description.

You can also do it the same way as from LMS7_Device class:
LMS_WriteParam(device,LMS7param(CMIX_BYP_RXTSP),1);

**Comment by f4exb** [comment]
Maybe you want to make this more explicit or have a dedicated API

**Comment by f4exb** [comment]
Yes using LMS_WriteParam is probably more simple and straightforward
