### ISSUE TITLE
connectivity issue with Lime Suite GUI

### ISSUE THREAD

**Issue by usmanfarooq948** [myriadrf/LimeSuite#132]
I am working on GUI of Lime Suite. I am facing a an issue of connectivity of Lime Suite GUI Application with LMS7002m 
EVB Ver 2 hardware.

Old version of Lime Suite i:e Version: 16.3.804 is successfully detected the LMS7002 hardware device. As shown in diagram (s) below.

![lms gui_old](https://user-images.githubusercontent.com/15828320/27682958-dcc0f774-5cdd-11e7-958c-4b9d968c6fed.PNG)
![device status](https://user-images.githubusercontent.com/15828320/27682974-ece4b334-5cdd-11e7-8a7c-599302a03a8e.PNG)
also showing ports in connection window (as shown in image below).

![connection old](https://user-images.githubusercontent.com/15828320/27683611-092331cc-5ce0-11e7-856b-fcfbe2e96290.PNG)

But in latest Lime Suite GUI Application version i:e 16.12.0-gd3b59691. It is unable to connect with 
 LMS7002 hardware device . Even not showing ports. As shown in below image.

![in project](https://user-images.githubusercontent.com/15828320/27683620-1a15b0cc-5ce0-11e7-9a95-8f341f0e738a.PNG)

Kindly purpose me a solution of above mentioned issue.

**Comment by IgnasJarusevicius** [comment]
Binary builds on GitHub are now longer updated.
If you are using older chip revision (LMS7002mr2), try:
http://downloads.myriadrf.org/builds/limesuite/LimeSuiteGUI_MR2_478db355.exe
or if you have recent board with new chip ((LMS7002mr3):
http://downloads.myriadrf.org/builds/limesuite/LimeSuiteGUI_20170616_6524d2.exe
If you are compiling from source, COM connection is not enabled by default, you need to enable it in CMake (set ENABLE_EVB7COM to true).

**Comment by usmanfarooq948** [comment]
Thanks for helping sir, Kindly provide me source of Lime Suite for LMS7002mr3.

**Comment by IgnasJarusevicius** [comment]
You can get source code for Lime Suite from master (latest) or stable (more testing done) branch. If you want exact commit for the binary version linked above, its filename contains part of git commit hash (use 'git checkout 6524d2')

**Comment by usmanfarooq948** [comment]
Respected sir please give me the guide(including examples of RX and TX) of LimeSuiteGUI_20170616_6524d2.exe

**Comment by IgnasJarusevicius** [comment]
Closing old issue.
