### ISSUE TITLE
Debugung LimeSuite

### ISSUE THREAD

**Issue by usmanfarooq948** [myriadrf/LimeSuite#133]
when i run LimeSuite in debugging mode an error is generated.
![debug](https://user-images.githubusercontent.com/15828320/27812762-b6eebde6-608a-11e7-96ba-6d16dca5d22c.PNG)

**Comment by rjonaitis** [comment]
LimeSuite is just a library, to debug it you have to start application which is using it. In this case you have to select LimeSuiteGUI for debugging.
