### ISSUE TITLE
Raspbian build fails with c++: error: unrecognized command line option ‘-mfpmath=both’

### ISSUE THREAD

**Issue by 9600** [myriadrf/LimeSuite#143]
See:
https://discourse.myriadrf.org/t/gcc-g-error/1536

**Comment by IgnasJarusevicius** [comment]
Hi, 
I have added a check so now '-mfpmath' option is set by default on x86 CPUs only. Before, it was possible to compile it on Raspbery PI by running CMake command: 
cmake -DENABLE_SIMD_FLAGS=none ..

**Comment by vatrat** [comment]
@IgnasJarusevicius This sounds like it's been fixed. Should this be closed?
