### ISSUE TITLE
copy and paste typo ?

### ISSUE THREAD

**Issue by martinzsmith** [myriadrf/LimeSuite#148]
The exact same 4 lines are repeated twice: https://github.com/myriadrf/LimeSuite/blob/master/SoapyLMS7/Settings.cpp#L424
https://github.com/myriadrf/LimeSuite/blob/master/SoapyLMS7/Settings.cpp#L429

And also:
https://github.com/myriadrf/LimeSuite/blob/master/SoapyLMS7/Settings.cpp#L449
https://github.com/myriadrf/LimeSuite/blob/master/SoapyLMS7/Settings.cpp#L454

**Comment by guruofquality** [comment]
thanks! https://github.com/myriadrf/LimeSuite/commit/6cdf7f32deebd57d6544d7ec3a3f54f43360d15f
