### ISSUE TITLE
"Saturated" sample points on channel A I-phase for HBD bypass setting (LimeSDR)

### ISSUE THREAD

**Issue by milestone12** [myriadrf/LimeSuite#150]
Can someone please help me understand why I get these "saturated" samples in channel A I-phase waveforms once I set the HBD ratio to _Bypass_ on LimeSDR.
![hbd bypass channel a cutout](https://user-images.githubusercontent.com/31235733/32982559-b747315c-cc86-11e7-8285-91381b40c12d.png)

Am I possibly missing another crucial setting?

For comparison, channel B with identical settings looks like:
![hbd bypass channel b cutout](https://user-images.githubusercontent.com/31235733/32982583-04ba09aa-cc87-11e7-97f7-b7abda9d1dd0.png)

**Comment by IgnasJarusevicius** [comment]
Closing old issue. 
No one has replied and I am not sure if using bypass mode with LimeSDR-USB was supported at all when this question was asked. Anyway, I remember implementing some additional setting changes for bypass mode (e.g. 43b84084e58fe9167e030) so it is not enough to flip HBD setting to make it work correctly.
