### ISSUE TITLE
Incorrect comment about performanceLatency in SoapyLMS7

### ISSUE THREAD

**Issue by DasSidG** [myriadrf/LimeSuite#155]
Hi,

This is a pretty trivial issue, but it did trip me up for a while. In SoapyLMS7, at [this point](https://github.com/myriadrf/LimeSuite/blob/fe53178a3c74ce983ca8314c582c0547f723ec20/SoapyLMS7/Streaming.cpp#L135) the comment states that 0 gives highest throughput, and 1 gives lowest latency. However, this is (as I understand it) in direct contradiction with [this section](https://github.com/myriadrf/LimeSuite/blob/fe53178a3c74ce983ca8314c582c0547f723ec20/src/lime/LimeSuite.h#L1053). 

In addition, looking at [this section](https://github.com/myriadrf/LimeSuite/blob/04b57e0a247debb451b067b3fc486307627ba5b7/src/protocols/ILimeSDRStreaming.cpp#L442) it would make sense that smaller tx and rx batch sizes (i.e. a lower value of throughputLatency) would give lower latency but lower throughput, so I believe that the comment in LimeSuite.h is correct, and the comment in Streaming.cpp is incorrect.

Obviously not an urgent or big fix, but might stop someone else in the future from wasting a bit of time like I did.

Thanks!

DasSidG

**Comment by IgnasJarusevicius** [comment]
corrected in d6bc28fdf6cb
