### ISSUE TITLE
Basic information should possibly be mirrored

### ISSUE THREAD

**Issue by vatrat** [myriadrf/LimeSuite#158]
I just received a USB LimeSDR. The LimeSDR wiki at wiki.myriadrf.org is currently down. It seems like it would be beneficial, whether for redundancy or for futureproofing, to keep a copy of basic information like build and install instructions in the readme file. This is of course optional, but I thought the point should be raised.

**Comment by IgnasJarusevicius** [comment]
build instructions are also in LimeSuite /docs folder
https://github.com/myriadrf/LimeSuite/blob/master/docs/Lime_Suite_Compilation_Guide.pdf
