### ISSUE TITLE
LimeSDR mini: Tx: limitation on minimum host sample rate

### ISSUE THREAD

**Issue by f4exb** [myriadrf/LimeSuite#159]
Hello, 
I am the main developper of SDRangel as some may already know. I can play with both the "big" LimeSDR and the LimeSDR mini and noticed what seems to be a limitation in the minimum host sample rate that can be used in transmission mode for the mini. Below 2.5 MS/s my program starts to malfunction and produces garbage. This does not happen with the "big" LimeSDR on which I have successfully tried rates as low as 768 kS/s. Since the only difference is the hardware connected I am wondering if this is a known limitation or if there is anything different in LimeSuite or the firmware that changes something in the interface preventing it to work below 2.5 MS/s for the LimeSDR mini. And of course if this is the case would it be possible to correct it so that the LimeSDR mini can also work at lower host sample rates.
Best regards, Edouard.

**Comment by IgnasJarusevicius** [comment]
Closing old issue. We have not observed this behaviour anywhere else. LimeSDR-Mini has never been limitted to >2.5 MSps sample rate. It should work with ~100 kSps.
