### ISSUE TITLE
LimeSDR-Mini TX API in SoapySDR seems incomplete

### ISSUE THREAD

**Issue by cdeletre** [myriadrf/LimeSuite#169]
Hi,

I want to use osmo-trx with a LimeSDR-Mini. It's working with a LimeSDR MIMO (not the Mini variant, so let's call it "Big" to clearly identify them) but with a LimeSDR-Mini it crashes a few tens of seconds. I've wanted to troubleshoot the issue by myself so I've started using SoapySDRUtil rate testing to check the LimeSDR-Mini stability: 

=> RX and TX rate measurements with the "Big" one are OK. With a requested rate of 1 Msps I get about 4 MBps (1 Msps I/Q CF16 on one channel) 

=> RX rate measurements with the "Mini" is also OK. With a requested rate of 1 Msps I get about 4 MBps (1 Msps I/Q CF16 on one channel).

=> TX rate measurements with the "Mini" gives me incoherent measurements. With a requested rate of 1 Msps I get about 32 MBps.

1 / I wonder where is the issue. Is it in the LMS7 Soapy driver or in the SoapySDR part ? So I'm stuck there.
2/ I wonder also why "Mini" is reporting a 40 MHz Reference clock while the "Big" is reporting 30.72MHz. Is it normal ?

Here are the tests I've made ("Rx:" and "Tx:" reports come from the debug I activated in LMS7 soapy driver):
[SoapySDRUtil-big-1Msps-RX.txt](https://github.com/myriadrf/LimeSuite/files/1775604/SoapySDRUtil-big-1Msps-RX.txt)
[SoapySDRUtil-big-1Msps-TX.txt](https://github.com/myriadrf/LimeSuite/files/1775605/SoapySDRUtil-big-1Msps-TX.txt)
[SoapySDRUtil-mini-1Msps-RX.txt](https://github.com/myriadrf/LimeSuite/files/1775606/SoapySDRUtil-mini-1Msps-RX.txt)
[SoapySDRUtil-mini-1Msps-TX.txt](https://github.com/myriadrf/LimeSuite/files/1775607/SoapySDRUtil-mini-1Msps-TX.txt)

Also I attach my log from osmo-trx if it can help:
[osmo-trx-big-UHD3.10.txt](https://github.com/myriadrf/LimeSuite/files/1775610/osmo-trx-big-UHD3.10.txt)
[osmo-trx-big-UHD3.11.txt](https://github.com/myriadrf/LimeSuite/files/1775611/osmo-trx-big-UHD3.11.txt)
[osmo-trx-mini-UHD3.10.txt](https://github.com/myriadrf/LimeSuite/files/1775612/osmo-trx-mini-UHD3.10.txt)
[osmo-trx-mini-UHD3.11.txt](https://github.com/myriadrf/LimeSuite/files/1775613/osmo-trx-mini-UHD3.11.txt)

**Comment by IgnasJarusevicius** [comment]
Just checked latest LimeSuite release (19.04) with  'SoapySDRUtil --rate' and both LimeSDR-Mini and LimeSDR-USB reports sample rates and data transfer rates correctly. So this issue seems no longer relevant. Closing.
