### ISSUE TITLE
LMS_GetSampleRateRange() returns bogus upper bound

### ISSUE THREAD

**Issue by laf0rge** [myriadrf/LimeSuite#187]
When calling the LMS_GetSampleRateRange() API, I get the following results for both LimeSDR-USB and LimeSDR-mini:

Sample Rate: Min=100000 Max=8e+07 Step=4.66239e-310

80MHz is unrealistic as a sample rate over USB 3.0, and the data sheets for LimeSDR-USB states 61MS/s vs LimeSDR-mini 30.72MHz.

Isn't the entire point of this API that an application can discover the capabilities of the connected hardware at runtime?

**Comment by IgnasJarusevicius** [comment]
I have updated API to return range values that match specification (2db5552c8a01e)
