### ISSUE TITLE
Excessive warnings building on OSX

### ISSUE THREAD

**Issue by orinem** [myriadrf/LimeSuite#192]
I suggest disabling this warning.  There are hundreds of them; the output below is merely representative.  Makes it difficult to see any real issue.

In file included from /LimeSuite/src/lms7002m_mcu/MCU_BD.cpp:13:
/LimeSuite/src/protocols/LMS64CProtocol.h:28:24: warning: 'GetDeviceInfo' overrides a member function but is not
      marked 'override' [-Winconsistent-missing-override]
    virtual DeviceInfo GetDeviceInfo(void);
                       ^
/LimeSuite/src/ConnectionRegistry/IConnection.h:93:24: note: overridden virtual function is here
    virtual DeviceInfo GetDeviceInfo(void);
                       ^

**Comment by IgnasJarusevicius** [comment]
I don't use OSX, but I only see a few warnings on Ubuntu with gcc, so its compiler dependant. Also, I think extra warnings flag was removed from release build some time ago, so maybe it produces less warnings now (I think it should no longer produce "missing override" warning). 
Anyway, as long as it works correctly, warnings are not really a big issue.
