### ISSUE TITLE
SISODDR for LimeSDR-Mini

### ISSUE THREAD

**Issue by gasparka** [myriadrf/LimeSuite#204]
49d518e706a6a5c64e7ebaace81432ea9580847a adds interpolation/decimation support for SISODDR mode, but only for LimeSDR. Any reasons to not support LimeSDR-Mini?

Code that disables SISODDR for LimeSDR-Mini:
https://github.com/myriadrf/LimeSuite/blob/master/src/API/LimeSDR_mini.cpp#L211

**Comment by IgnasJarusevicius** [comment]
this was addressed with ddae8b9892013cb2783d19348f823
