### ISSUE TITLE
LimeSDR mini TX has dependency on RX channel config

### ISSUE THREAD

**Issue by maximevince** [myriadrf/LimeSuite#211]
While using limeplayer from gps-sdr-sim, with a recent LimeSuite version on the LimeSDR mini,
I found that TX streaming is not working at the right speed.

I found that reverting to right before this patch, fixed the problem:
https://github.com/myriadrf/LimeSuite/commit/52d61291f789c7bba070da2642be93aa9dcd6621

Distilled from this patch, I found it is actually this line which makes it work again on a recent LimeSuite version:
`lms->Modify_SPI_Reg_bits(LMS7param(PD_RX_AFE1), 0);` 
Adding this back in:
`int Streamer::UpdateThreads(bool stopAll)`
Fixed the problem.

There seems to be some dependency within the LimeSDR Mini to get the TX channel streaming at the right rate, and this RX channel power-down register setting...

Is this a known issue?

Also see:
https://github.com/osqzss/gps-sdr-sim/issues/161

**Comment by IgnasJarusevicius** [comment]
should be resolved by c3af81d330c8962e6cb32d25caa40e46c995629d
