### ISSUE TITLE
Feature Request: Remove dependency on GUI

### ISSUE THREAD

**Issue by laf0rge** [myriadrf/LimeSuite#215]
On production systems in cellular infrastructure, you neither wont nor have any kind of GUI.  I find it rather cumbersome that there are many things for which LimeSuite requires a GUI.

In fact, the LimeSuite should compile without any dependency on any graphical toolkit installed on the system at all.

There don't seem to be command line utilities for the most basic of tasks, such as retrieving the version of  the currently running gateware. A commandline utility can be used on headless systems, and it can be used from scripts, etc.

**Comment by FFY00** [comment]
LimeSuite does compile without the presence of any graphical toolkit.

Here's the tree of such installation:
```
etc
 └─udev
    └─rules.d
       └─64-limesuite.rules
usr
 ├─bin
 │  └─LimeUtil
 ├─include
 │  └─lime
 │     ├─ADCUnits.h
 │     ├─ADF4002.h
 │     ├─ConnectionHandle.h
 │     ├─ConnectionRegistry.h
 │     ├─FPGA_common.h
 │     ├─IConnection.h
 │     ├─LMS64CCommands.h
 │     ├─LMS64CProtocol.h
 │     ├─LMS7002M.h
 │     ├─LMS7002M_RegistersMap.h
 │     ├─LMS7002M_parameters.h
 │     ├─LMSBoards.h
 │     ├─LimeSuite.h
 │     ├─LimeSuiteConfig.h
 │     ├─Logger.h
 │     ├─MCU_BD.h
 │     ├─MCU_File.h
 │     ├─Si5351C.h
 │     ├─Streamer.h
 │     ├─SystemResources.h
 │     ├─VersionInfo.h
 │     ├─dataTypes.h
 │     ├─fifo.h
 │     └─lms7_device.h
 └─lib
    ├─SoapySDR
    │  └─modules0.6
    │     └─libLMS7Support.so
    ├─cmake
    │  └─LimeSuite
    │     ├─LimeSuiteConfig.cmake
    │     └─LimeSuiteConfigVersion.cmake
    ├─libLimeSuite.so
    ├─libLimeSuite.so.18.06-1
    ├─libLimeSuite.so.18.06.0
    └─pkgconfig
       └─LimeSuite.pc
```

I do agree with you that command line tools should be available.
