### ISSUE TITLE
underrun not properly set / overrun overwritten

### ISSUE THREAD

**Issue by maschi01** [myriadrf/LimeSuite#217]
I noticed that stats.overrun was set twice with different variables.
Possible that the second line should say
stats.underrun = underflow;

https://github.com/myriadrf/LimeSuite/blob/d6b0371fc074f71fac2ccd43e1e7b6220657fe7c/src/protocols/Streamer.cpp#L113-L114

Regards,
Martin

**Comment by IgnasJarusevicius** [comment]
fixed with 2d43f04d858e7ccb953ef3758948377214196feb
