### ISSUE TITLE
timestamps always enabled

### ISSUE THREAD

**Issue by lryindra** [myriadrf/LimeSuite#219]
Streamer::UpdateThreads always enabled SYNCH_DIS from register 0x0008 in the LimeSDR-Mini Gateway FPGA. SYNCH_DIS enables or disables packet synchronization using timestamps.  Register 0x0008 is the DIQ interface control. 

I expect this setting to be controlled by waitForTimestamp in lms_stream_meta_t.

**Comment by IgnasJarusevicius** [comment]
It is correct behavior. SYNCH_DIS should always be 0 under normal circumstances and packet synchronization should be controlled by a flag (set by waitForTimestamp) in stream packet header. SYNCH_DIS=1 is only for debugging in case we suspect that sync flag gets corrupted or is not interpreted correctly by FPGA.
