### ISSUE TITLE
LimeQuickTest issues

### ISSUE THREAD

**Issue by FFY00** [myriadrf/LimeSuite#225]
I feel like some sort of check should be added to `LimeQuickTest` to ensure a device is connected.

Right now I get the following outputs:

No device connected.
```
[ TESTING STARTED ]
->Start time: Fri Oct  5 19:22:46 2018

Listening on port: 5000
Started listening thread
connect failed with error: -1
connect failed with error: -1
connect failed with error: -1
connect failed with error: -1
->Device: Remote, media=TCP, module=Z_Remote
Warning: USB3 not available
  Serial Number: 
connect failed with error: -1
connect failed with error: -1
Failed to connect
```

Device connected (Only 1 device donnected!)
```
[ TESTING STARTED ]
->Start time: Fri Oct  5 19:24:50 2018

Error: Multiple Devices Connected
Failed to connect
```

**Comment by IgnasJarusevicius** [comment]
LimeQuickTest wants only one connection to be present. It seems you have ConnectionRemote enabled that always adds one connection to the list. It was introduced for debugging/testing purposes and should be disabled in normal build.

**Comment by FFY00** [comment]
Is that `STREAM_UNITE`?

**Comment by rjonaitis** [comment]
You should disable `ENABLE_REMOTE`

**Comment by IgnasJarusevicius** [comment]
LimeQuickTest should now connect the first device instead of failing when more than one possible connection is detected (1bfa380aeb7d3d08f6e7341911095da9fae886fb). This makes it possible to still run LimeQuickTest with ConnectionRemote enabled ('ENABLE_REMOTE').
