### ISSUE TITLE
Octave Plugin build pulls library from wrong location

### ISSUE THREAD

**Issue by ChuckM** [myriadrf/LimeSuite#236]
When building the repository the octave plugin build trys to pull libLimeSuite.so from the library path (`/usr/lib;/usr/local/lib`) rather than from the build itself. If this is a first time build of the repository everything fails, if it is being built where the repository has been previously installed, it will link the octave plug-in against the **installed** library rather than linking it against the **freshly built** library. 

You can reproduce by building on a clean system, or by renaming the installed libLimeSuite.so file, the failure is a linker error during the octave plugin build.

**Comment by rjonaitis** [comment]
Fixed: f0616e11650db47a5f2d7943f2fe8477b9
