### ISSUE TITLE
LMS7 Soapy module readstream calls freeze when changing sample rate

### ISSUE THREAD

**Issue by Dantali0n** [myriadrf/LimeSuite#251]
Please read for reference: https://github.com/cjcliffe/CubicSDR/issues/716

In CubicSDR `setSampleRate` is called after calling `activateStream` at higher sampling rates (> 3Mhz) this will cause `readstream` to no longer return samples. We have found that calling `deactivateStream` followed by `activateStream` resolves this issue. 

I feel that the LMS7 Soapy module should handle the `setSampleRate` call in such a way that it will perform proper re initialization on an active device.

**Comment by rjonaitis** [comment]
Closing issue, sampling rate should not be changed while streaming is active.
Cubic SDR already has implemented correct sample rate change handling (stopping and restarting stream during rate change).
