### ISSUE TITLE
Important fix : throughputVsLatency is not handled on Tx

### ISSUE THREAD

**Issue by F5OEO** [myriadrf/LimeSuite#264]
throughputVsLatency influence number of FPGA sample batch in .
On litlle Soc like Raspberry Pi, this help a lot to decrease the CPU.
After investigation there is a mistake here : 
https://github.com/myriadrf/LimeSuite/blob/abf8214056f059764669ea9d7755edac8752a047/src/protocols/Streamer.cpp#L646
And should be replaced by
    const uint8_t packetsToBatch = dataPort->CheckStreamSize(**txBatchSize**);

After this fix, higher SampleRate could be transmit on litlle SOC (around 8MS on LimeNetMicro)

**Comment by IgnasJarusevicius** [comment]
Thanks for noticing this. Fixed 8efa0c5a94e5b1148ba9f88074bc90f30a0ecadd
