### ISSUE TITLE
lms_stream_status_t.droppedPackets 

### ISSUE THREAD

**Issue by netdoggy** [myriadrf/LimeSuite#267]
https://github.com/myriadrf/LimeSuite/blob/26de12a4f7e21a5fe938f2b915fe46e10d62dd58/src/lime/LimeSuite.h#L1108

it seems that after calling LMS_GetStreamStatus function, droppedPackets is cleared, it seems to me that this should be indicated in the comments and in the documentation.

https://github.com/myriadrf/LimeSuite/blob/54614dae7e7c7bf999d5cf69222090c1aef4f7e0/src/protocols/Streamer.cpp#L105

**Comment by IgnasJarusevicius** [comment]
Comments has been updated recently to state that its dropped Packets since the last call to LMS_GetStreamStatus.
 https://github.com/myriadrf/LimeSuite/blob/master/src/lime/LimeSuite.h#L1104
