### ISSUE TITLE
LimeQuickTest without QUICKTEST_GUI doesn't output anything

### ISSUE THREAD

**Issue by sw** [myriadrf/LimeSuite#270]
When `QUICKTEST_GUI` is not defined, LimeQuickTest will not output anything.

The problem seems to be the linker pragma, see attached patch. I must admit that I have not investigated this thoroughly.
[0001-Don-t-hide-console-when-QUICKTEST_GUI-is-not-defined.patch.txt](https://github.com/myriadrf/LimeSuite/files/3406228/0001-Don-t-hide-console-when-QUICKTEST_GUI-is-not-defined.patch.txt)

**Comment by IgnasJarusevicius** [comment]
Thanks, for noticing this. I have never noticed that it does not output to windows command prompt or powershell It was outputting to git bash console so (which was easiest to launch for me).
