### ISSUE TITLE
LimeRFE branch compilation issue

### ISSUE THREAD

**Issue by F5OEO** [myriadrf/LimeSuite#274]
Branch RFE : 
[ 25%] Building CXX object src/CMakeFiles/LimeSuite.dir/API/lms7_api.cpp.o
/home/pi/dvbsdr/build/LimeSuite/src/API/lms7_api.cpp:3:31: fatal error: limeRFE_constants.h: No such file or directory
 #include "limeRFE_constants.h"

Quick solution is to copy src/limeRFE/limeRFE_constants.h to src/API but should be better to add PATH to cmake.

**Comment by IgnasJarusevicius** [comment]
As far as I can tell the issue was only with GUI disabled, right? It should be fixed with abd45cd9c84842ef6c0650465549f5673073ebca .
