### ISSUE TITLE
Add basic signal generator to LimeSuiteGUI

### ISSUE THREAD

**Issue by 9600** [myriadrf/LimeSuite#281]
See:

https://discourse.myriadrf.org/t/limesdr-mini-test-signal/5015/2

**Comment by IgnasJarusevicius** [comment]
I have added an option to transmit signal from software for WFM playback in 
127f1e2c09426e03b808ab08ef1f4c532c15d128

**Comment by ra1nb0w** [comment]
very nice idea to have sin/cw signal generator

**Comment by gracid** [comment]
Seems to be implemented, closing.
