### ISSUE TITLE
after "sudo make install", command"install.sh", command not found

### ISSUE THREAD

**Issue by jin-github102** [myriadrf/LimeSuite#283]
after installingss, i met this.  Do you know whats wrong??

dell@dell-XPS-15-9550:~/LimeSuite/udev-rules$ ls
64-limesuite.rules  install.sh
dell@dell-XPS-15-9550:~/LimeSuite/udev-rules$ sudo ./install.sh
sudo: ./install.sh: command not found
dell@dell-XPS-15-9550:~/LimeSuite/udev-rules$ sudo install.sh
sudo: install.sh: command not found
dell@dell-XPS-15-9550:~/LimeSuite/udev-rules$ ls -l
total 8
-rw-rw-r-- 1 dell dell 471 Oct 29 18:46 64-limesuite.rules
-rw-rw-r-- 1 dell dell  99 Oct 29 18:45 install.sh

**Comment by btashton** [comment]
@IgnasJarusevicius  Looks like when this restructure branch got merged in commit c02f4358b6eb3a83f333e8951419f34b18667dde some scripts lost there execute bit.

@jin-github102 `chmod +x ./install.sh` then try running it.

**Comment by IgnasJarusevicius** [comment]
I have not noticed that execute flag got lost in that commit  about 1.5 years ago as I always used 'sudo sh install.sh'. I am going to add/bring back the flag.

**Comment by jin-github102** [comment]
It works after using "sudo sh install.sh. 
I didnt try the other way. I think it will work too. 
Thank you very mush! @IgnasJarusevicius @btashton
