### ISSUE TITLE
STREAM - faster calibration recovery options

### ISSUE THREAD

**Issue by guruofquality** [myriadrf/LimeSuite#31]
I was thinking about a way to remove some of the lag from the calibration sequence. Specifically stopping the threads, disabling FPGA streaming, re-enabling streaming, and then re-restarting the threads. Emphasis on the threads being brought up and down.

There is an issue of the MCLK during calibration being wrong, or too high. The LML clock dividers could be set to match, or the MCLK output could be disabled during calibration. Personally, I'm afraid of any clock glitchiness, I would have configurable enables on everything in the MCLK domain to disable the entire FPGA+LML interface during cal.

My hope is that if the changing clock rate can be removed from the list of issues, that everything else can be left "as-is" during calibration.

**Comment by rjonaitis** [comment]
Streaming threads are no longer stopped during calibration, only the USB transfers and FPGA streaming are disabled/enabled.
