### ISSUE TITLE
periphcfg_module - BOARD_GPIO_OVRD "dedicated function"

### ISSUE THREAD

**Issue by manuelpreuschoffprma1025** [myriadrf/LimeSuite#326]
I am trying to set the LimeSDR USB J12 GPIO Pins depending on the rx/tx status. In the FPGA Gateware Description i found the register map of the periphcfg_module. Register 0x00C0 sets the GPIO control override "mode". Default is 1 for all 8 GPIO pins, so the pins can be overrided by user. But what is the dedicated function of each pin? In https://github.com/myriadrf/LimeSuite/issues/149 that the dedicated function of GPIO_0 pin is TX-Stream indication. What about the other pins? Is there a documentation going further than the FPGA hardware description?

Thank you in advance, 
Manuel

**Comment by ztamosevicius** [comment]
Other functions are as follows:
GPIO0 - Tx/Rx stream indication
GPIO1 - Rx PLL Lock
GPIO2 - Tx PLL Lock
GPIO3 - Packet loss flag
GPIO4 - GPIO7 - No special function, reserved
