### ISSUE TITLE
Setting Clock Reference

### ISSUE THREAD

**Issue by herlesupreeth** [myriadrf/LimeSuite#328]
https://github.com/myriadrf/LimeSuite/blob/1480bfeaf4de211c40813fc5ca161b1b644778ec/src/API/lms7_device.cpp#L1572

shouldn't it be lime::LMS7002M::Rx rather than lime::LMS7002M::Tx in the above code ? Please let me know if my understanding is wrong

**Comment by rjonaitis** [comment]
In this case the Tx/Rx parameter doesn't matter, they share the same reference clock https://github.com/myriadrf/LimeSuite/blob/d5a5c1f179460d6c6fe876d2e6c9dc7ba7479732/src/lms7002m/LMS7002M.cpp#L1059-L1063
