### ISSUE TITLE
runtime loading for user-created connection modules

### ISSUE THREAD

**Issue by guruofquality** [myriadrf/LimeSuite#33]
We want to support dynamic expansion of the connections available in the connection registry. This is so user's can use the stock LMS7002m driver DLL/binaries and expand for their own creation.
- [ ] support scanning runtime directory for user generated DLLs
- [ ] hooks to control and modify runtime directory path (like env variable)
- [ ] example connection module with cmake file

**Comment by IgnasJarusevicius** [comment]
Closing old issue. Re-open if still relevant.
