### ISSUE TITLE
Is it possible to install LimeSuite on PetaLinux?

### ISSUE THREAD

**Issue by rodrirq** [myriadrf/LimeSuite#343]
Hi, i'm trying to install LimeSuite on PetaLinux. I'm following the "building from software" steps, but i don't know how to cross compile using cmake and I don't even know if is possible to do it.
 I hope someone has an idea, thank you.

**Comment by 9600** [comment]
Should be possible, yes, but this is really a question for the PetaLinux community/developers and building Lime Suite for this should be no different to building any other Linux software which they don't provide by default. I'm afraid this is not something that we can help you with.

**Comment by rodrirq** [comment]
Thank you for your answer, I will keep investigating.
