### ISSUE TITLE
Compiler errors and fixes with wxWidgets 3.1.5

### ISSUE THREAD

**Issue by Min4sT1r1th** [myriadrf/LimeSuite#348]
There are some compiler errors, when trying to build the software against wxWidgets 3.1.5.
Pull requests against my fork are available here:

https://github.com/Min4sT1r1th/LimeSuite/pulls

**Comment by rjonaitis** [comment]
For future contributions, please create a pull request directly on the repository you want to suggest your code and not on your forked repository.
