### ISSUE TITLE
dualRXTX fails for LimeNET micro

### ISSUE THREAD

**Issue by grcasanova** [myriadrf/LimeSuite#351]
The command fails with the following error

```
$ sudo ./dualRXTX
Devices found: 1
Reference clock 30.72 MHz
Number of RX channels: 1
Number of TX channels: 1
Invalid channel number.
```

Running on a Raspberry Pi CM3 with ubuntu 20.04 LTS installed.
LimeSuite compiled with no errors from source.

**Comment by 9600** [comment]
It's probably because you're trying to run a MIMO example on a SISO platform; LimeNET Micro does not have a second channel.
