### ISSUE TITLE
TravisCI needs update

### ISSUE THREAD

**Issue by rjonaitis** [myriadrf/LimeSuite#353]
Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

@9600 TravisCI can only be set up by repository owner.

**Comment by rjonaitis** [comment]
TravisCI replaced with GitHub actions 90ff379

**Comment by 9600** [comment]
Many thanks!

Where do we see whether the build is successful or failing? Is there a badge we can add to README.md?

**Comment by 9600** [comment]
Great, thanks.

I see that all three GH Actions O/S builds seem to be successful, but AppVeyor, which we have been using up until now for Windows, is failing. Maybe we should remove this if GHA can take care of all three including Windows?

**Comment by rjonaitis** [comment]
@9600 I've fixed the failure on AppVeyor, but since we now have all O/S building with GH actions, it's redundant and can be removed. I've deleted the appveyor.yml configuration, but I don't have permissions to the repository settings to disable it completely, you'll have to do that.
