### ISSUE TITLE
Compile error in "LMS64CProtocol_remote.cpp"

### ISSUE THREAD

**Issue by gvanem** [myriadrf/LimeSuite#355]
Compiling `LMS64CProtocol_remote.cpp` using MSVC, I get a long list of errors related to missing Winsock stuff:
```
LMS64CProtocol_remote.cpp(30): error C2065: 'WSADATA': undeclared identifier
LMS64CProtocol_remote.cpp(30): error C2146: syntax error: missing ';' before identifier 'wsaData'
LMS64CProtocol_remote.cpp(30): error C2065: 'wsaData': undeclared identifier
LMS64CProtocol_remote.cpp(31): error C2065: 'wsaData': undeclared identifier
LMS64CProtocol_remote.cpp(31): error C3861: 'WSAStartup': identifier not found
LMS64CProtocol_remote.cpp(35): error C2065: 'AF_INET': undeclared identifier
...
```

An easy fix for me was to patch like so:
```diff
--- a/src/ConnectionRemote/LMS64CProtocol_remote.cpp 2020-11-09 14:19:06
+++ b/src/ConnectionRemote/LMS64CProtocol_remote.cpp 2021-12-20 10:41:32
@@ -8,6 +8,7 @@
 #include <netinet/in.h>
 #include <arpa/inet.h>
 #else
+#include <winsock2.h>
 #include <windows.h>
 #endif
 #include <fcntl.h>
```

What's up with this? Isn't this file supposed to be for Windows?

*Edit*: I just discovered a `-D_WIN32_LEAN_AND_MEAN` had sneaked in (from `%CL%`). Removing that, it compiles.
        &nbsp; &nbsp;&nbsp; &nbsp;  But IMHO it's better to force the use `<winsock2.h>` in this day and age.

**Comment by rjonaitis** [comment]
Remote connection was intended for internal use only, it has been removed from compilation targets https://github.com/myriadrf/LimeSuite/commit/cfc53ed6433305e807dc161a9a9c81b868bf829e
