### ISSUE TITLE
The port is busy. Connection LimeRFE + LimeSDR

### ISSUE THREAD

**Issue by egortaran** [myriadrf/LimeSuite#367]
## Issue Description
Hello everyone. I would like to run srsRAN on LimeSDR v1.4s using LimeRFE amplifier. How to do it?
I use this [documentation](https://github.com/myriadrf/LimeRFE/tree/master/hardware/1v31/docs). When I use LimeSuite GUI, following the instructions, the ports open. 

<details>
  <summary>LimeSDR</summary>

  ```
INFO: Disconnected control port
INFO: Reference clock 30.72 MHz
INFO: Connected Control port: LimeSDR-USB FW:4 HW:4 Protocol:1 GW:2.23 Ref Clk: 30.72 MHz
  ```
</details>

<details>
  <summary>LimeRFE</summary>

  ```
Port opened
Firmware version: 1
Hardware version: 0x10
  ```
</details>

But since the device is already busy, I can not be able to connect srsRAN.

<details>
  <summary>srsRAN</summary>

  ```
[ERROR] Cannot claim interface - Resource busy
[ERROR] Failed to open device
[ERROR] connection is not open
[ERROR] TransferPacket: Write failed (ret=0)
[ERROR] connection is not open
[ERROR] TransferPacket: Write failed (ret=0)
[ERROR] Failed to open. Device is busy.
Failed to create Soapy object
Error initializing radio.
  ```
</details>

## Technology stack
Ubuntu 22.04 (Intel® Core™ i7-7700 CPU @ 3.60GHz × 8)
srsRAN 22.04 (open5gs)
LimeSDR v1.4s (LimeSuite v20.10.0, SoapySDR 0.7.2)
LimeRFE 1v31

**Comment by 9600** [comment]
Don't use LimeSuiteGUI to open the LimeSDR and instead just use this to connect to the LimeRFE and configure it. That way the SDR will be free for srsRAN to open.
