### ISSUE TITLE
LimeSDR LED documentation and repurposing thoughts

### ISSUE THREAD

**Issue by guruofquality** [myriadrf/LimeSuite#44]
What is the purpose of the current LEDs near the usb connector. Perhaps FPGA and FX3 boot indicators? I was wondering about documenting it to help new users when they first power on the hardware.

Secondly, could any of the LEDs be re-purposed after boot as some kind of status indicator for things like:
- reference lock
- rx streaming
- tx streaming
- etc

**Comment by IgnasJarusevicius** [comment]
old issue. LED documentation can be found on wiki:
https://wiki.myriadrf.org/LimeSDR-USB_hardware_description#Indication_LEDs
