### ISSUE TITLE
Simultaneous support for both CyAPI and libusb

### ISSUE THREAD

**Issue by guruofquality** [myriadrf/LimeSuite#47]
This is more of a thought at the moment and note for the future: The current ConnectionSTREAM has a a dual implementation for both libusb and CyAPI separated by a lot of `#ifdef __unix__`.
- However it should be the case that any platform could be built for either api regardless. The ifdefs should reflect the API or rather we should have two separate ConnectionSTREAM<api> implementations for each rather than all of the ifdefs in one single implementation.
- And further, the way connection registry is handled, both ConnectionSTREAMLibUSB and ConnectionSTREAMCyAPI could be compiled at the same time -- Bladerf actually does this support for both as a redundancy when one usb library is causing a problem.

**Comment by IgnasJarusevicius** [comment]
Closing old issue. There are no plans to implement simultaneous CyAPI and libusb support for FX3.
