### ISSUE TITLE
Replace ini parse submodule with subtree

### ISSUE THREAD

**Issue by guruofquality** [myriadrf/LimeSuite#48]
Git subtree attempts to copy or squash another git repo -- rather than submodule which is more like a lightweight symlink. Should we consider replacing the ini parse submodule with subtree instead to

* eliminate some confusion when building from source (forgetting to run git submodule update)
* ensure that tarballs from github release tags are build-able (cant use git from a tarball)
  * example -- homebrew builds on osx using release tag tarballs from github

I like submodules a lot, but since this is the only case so far, it may be easier to go with subtree.

**Comment by guruofquality** [comment]
As an example, I did this for test on the reorganization branch in external/ directory: https://github.com/myriadrf/LimeSuite/tree/ReorgWork

**Comment by rjonaitis** [comment]
I agree, that would be more convenient for simple users
