### ISSUE TITLE
set github project page url

### ISSUE THREAD

**Issue by guruofquality** [myriadrf/LimeSuite#55]
@9600 There is a github project page url option. Can you set that to https://myriadrf.org/projects/lime-suite/? The option should show up when you are looked in on the main page: https://github.com/myriadrf/LimeSuite

**Comment by 9600** [comment]
Done.

If you could ping me once the [wiki page](http://wiki.myriadrf.org/Lime_Suite) is updated and I'll then update the project page based on this.
