### ISSUE TITLE
Add details to wiki.

### ISSUE THREAD

**Issue by 9600** [myriadrf/LimeSuite#56]
To start with, e.g. what is it, what hardware is supported and how to build/install. Eventually it would be good to document the API here.

**Comment by guruofquality** [comment]
Mostly in place. I need to fill in more sections and get some more cmake and lms7suite screenshots: http://wiki.myriadrf.org/Lime_Suite

**Comment by guruofquality** [comment]
Closing now. This is mostly what I though we needed, but there might be more. Please reopen if we need something else.
