### ISSUE TITLE
Add --fpga and --fw burn options to LimeUtil

### ISSUE THREAD

**Issue by guruofquality** [myriadrf/LimeSuite#60]
Create command line additions to the LimeUtil to support loading firmware when GUI is not an option.

**Comment by rjonaitis** [comment]
Programming options added, now programs the first available device. Still needs additional parameter to specify which device to program, or somehow combine it with --make or --find options.

**Comment by guruofquality** [comment]
added --args: https://github.com/myriadrf/LimeSuite/commit/9789a71beffc58802448c94b6df6ba2e26c6a39b
