### ISSUE TITLE
[Feature Request] Bluetooth LE (Low Energy) stack from Apache Mynewt for LimeSDR?

### ISSUE THREAD

**Issue by Hedda** [myriadrf/LimeSuite#65]
Just learned that the Apache Software Foundation has recently released version 0.9 Apache Mynewt open source real-time operating systems for micro-controllers under an Apache 2.0 license. This RTOS currently works on STMicro STM32 Cortex-M4 and Arduino Zero / M0 Cortex-M0 boards, but more interestingly they have also implemented the first open source Bluetooth Low Energy (BLE) stack for MCUs, (starting with support for Nordic Semi nRF52 Cortex-M4 and nRF51 Cortex-M1 evaluation boards), acting as a replacement for the previous closed source Nordic SoftDevice Bluetooth Smart / LE solution stack that used to use.

http://mynewt.apache.org

Suggest that this open source Bluetooth Low Energy (BLE) stack for MCUs could get ported and added to LimeSDR?

**Comment by IgnasJarusevicius** [comment]
Closing old issue. Not going to implement.
