### ISSUE TITLE
Minimum TX bandwidth limited to 5 MHz

### ISSUE THREAD

**Issue by vsergeev** [myriadrf/LimeSuite#71]
The LMS7002 datasheet suggests the TXLPFL path can be tuned down to 2 MHz, but the [code](https://github.com/myriadrf/LimeSuite/blob/008db1b4b771e50d0ab557bd86dc416a190478f1/src/lms7002m/LMS7002M_filtersCalibration.cpp#L25) sets a lower limit of 5 MHz. Is there is an implementation detail behind the discrepancy?

It would be nice to use the lower TX filter bandwidths for more narrowband signals, if they're available.

**Comment by rjonaitis** [comment]
The LMS7002 datasheet specifies TXLPFL frequencies in IF, while the code uses RF

**Comment by vsergeev** [comment]
Ah, so it looks like it's operating at a digital IF of at least 2.5 MHz?
