### ISSUE TITLE
GUI temperature reading wrong for LimeSDR

### ISSUE THREAD

**Issue by 9600** [myriadrf/LimeSuite#92]
Reporting a figure that is far too large in the base GUI, but one that appears reasonable elsewhere. See:

https://discourse.myriadrf.org/t/lime-suite-gui-temperature-check-very-wrong/662/1

**Comment by rjonaitis** [comment]
chip temperature reading updated for LimeSDR 1.4 in ca3d07b, not yet merged into master

**Comment by rjonaitis** [comment]
fix merged into master
